### ISSUE TITLE
VS Code development documentation

### ISSUE THREAD

**Issue by ryanmerolle** [arista-netdevops-community/docker-avd-base#11]
Many new netops minded users are dipping their toes into development using VS Code given its manageable learning curve and extensive extension list.

It would be good to look into the workflows for VS Code in regards to the remote extension workflows.  The reason I say this is because the AVD image recommends jumping into the container and using your cli based linux editor of choice.  

VS Code workflows allow you to manage containers and interface with containers a number of ways:

- Attach directly to container from host system, development, and run against said container (similar to the model avd development uses today)
- Edit files on the locally host system and run/test within the container by attaching an always on terminal view into the container. 
- SSH to a remote system using remote ssh extension & using one of the first 2 models
- Connect to WSL using remote wsl extension & using one of the first 2 models

It would be good to look at these workflows and see how documentation and Makefile could be slightly enhanced to guide new users with regards to VS Code as a platform agnostic IDE.  I will think about this and likely provide a PR in the coming weeks.  I just wanted to write something out before I forgot, and also allow Arista folk (I know there are a few from your webinars) that use VS code to chime in.

**Comment by titom73** [comment]
I have a test repository that implement devcontainer available at https://github.com/titom73/.devcontainer and usable with GH beta of codespace and local devcontainer.

This approach means 2 things:
- Which container to leverage which is the easiest thing in our context
- Build VScode environment as we need to configure wich modules to install to customize VSCode experience.

The last thing is very personal and even in our team, each of us uses our own set of modules :)

So if you don't mind, I would move this issue to `aristanetworks/ansible-avd` project as it will be a documentation effort for AVD to expose in its documentation.

We can certainly document following scenario:

- Attach directly to container from host system, development, and run against said container (similar to the model avd development uses today)
- SSH to a remote system using remote ssh extension & using previous model

For _Edit files on the locally host system and run/test within the container by attaching an always on terminal view into the container._, not sure I understand the difference with the previous ones.

Regarding WSL use case, let see if someone with a Windows system can document this approach.

**Comment by ryanmerolle** [comment]
All good points.

I would only comment that if a volume was setup to allow for .vscode directory to be shared with the container, users could maintain their personal extensions without this or any other project doing so for them.

**Comment by ryanmerolle** [comment]
For later reference:

- [VS Code Devcontainer](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host)
- [VS Code Docker via a remote Docker host](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host)

**Comment by titom73** [comment]
Hello @ryanmerolle 

A dedicated VSCode container is also available to work with AVD: https://github.com/arista-netdevops-community/docker-avd-vscode 

I will go ahead and close this issue feel free to reopen it if required.
